-- AlterTable
ALTER TABLE `item` ADD COLUMN `srsLevel` INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE `WkItem` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(191) NOT NULL,
    `en` VARCHAR(191) NOT NULL,
    `data` JSON NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
